<#
.SYNOPSIS
Build the Windows projects and generate NuGet packages

.DESCRIPTION
Build the Windows projects that were generated by GenerateVS2019.ps1 and generate the NuGet packages.

.EXAMPLE
BuildVS2019NuGet.ps1
#>

[CmdletBinding()]
param(
)

$ErrorActionPreference = "stop"

$MSbuildExe = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe"

function BuildPlatform($path)
{
    $fullPath = $PSScriptRoot + "/../build/" + $path
    if (-not (Test-Path $fullPath))
    {
        Write-Host "ERROR $fullPath does not exist"
        return
    }

    Push-Location $fullPath | Out-Null

    try
    {
        & $MSbuildExe lib3MF.sln /t:lib3MF_s /p:Configuration=Release
        & $MSbuildExe lib3MF.sln /t:lib3MF_s /p:Configuration=Debug
    }
    finally
    {
        Pop-Location
    }
}

function GenerateNuGet
{
    $nuget = "$PSScriptRoot/../build/nuget.exe"
    wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile $nuget
    . $nuget pack $PSScriptRoot/../build/buildwin32/nuget/windows/lib3mf.windows.nuspec -OutputDirectory $PSScriptRoot/../build/nuget
}

function Main
{
    BuildPlatform "buildwin32"
    BuildPlatform "buildwin64"
    BuildPlatform "buildwinarm64"
    BuildPlatform "builduwp32"
    BuildPlatform "builduwp64"
    BuildPlatform "builduwparm"
    BuildPlatform "builduwparm64"

    GenerateNuGet
}

Main
